version: '3'
services:
  nginx:
    build:
      context: ./api/docker
      dockerfile: nginx.docker
    volumes:
      - ./api:/var/www/api
    ports:
      - "8081:80"
  php-fpm:
    build:
      context: ./api/docker
      dockerfile: php-fpm.docker
    volumes:
      - ./api:/var/www/api
  php-cli:
    build:
      context: ./api/docker
      dockerfile: php-cli.docker
    volumes:
      - ./api:/var/www/api
    working_dir: /var/www/api
    tty: true

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
